"""Initial migration.

Revision ID: 52010809bc78
Revises: 
Create Date: 2024-11-23 23:32:19.009175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52010809bc78'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brokers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('currencies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exchanges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('security_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('securities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ticker', sa.String(length=10), nullable=False),
    sa.Column('currency_id', sa.Integer(), nullable=False),
    sa.Column('exchange_id', sa.Integer(), nullable=False),
    sa.Column('has_dividends', sa.Boolean(), nullable=True),
    sa.Column('security_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['currency_id'], ['currencies.id'], ),
    sa.ForeignKeyConstraint(['exchange_id'], ['exchanges.id'], ),
    sa.ForeignKeyConstraint(['security_type_id'], ['security_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('deals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('security_id', sa.Integer(), nullable=False),
    sa.Column('broker_id', sa.Integer(), nullable=False),
    sa.Column('deal_type', sa.String(length=10), nullable=False),
    sa.Column('deal_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['broker_id'], ['brokers.id'], ),
    sa.ForeignKeyConstraint(['security_id'], ['securities.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('deals')
    op.drop_table('securities')
    op.drop_table('security_types')
    op.drop_table('exchanges')
    op.drop_table('currencies')
    op.drop_table('brokers')
    # ### end Alembic commands ###
