"""Add price field to deals table

Revision ID: b1e37f3c27c9
Revises: 04303e3f4e2e
Create Date: 2024-11-24 00:26:41.131588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1e37f3c27c9'
down_revision = '04303e3f4e2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('deals', schema=None) as batch_op:
        batch_op.drop_column('price')

    # ### end Alembic commands ###
